# Generated by Django 5.1.7 on 2025-03-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('driver', 'Driver')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('availability', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('driver', models.OneToOneField(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to='system.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_latitude', models.FloatField(default=0.0)),
                ('pickup_longitude', models.FloatField(default=0.0)),
                ('dropoff_latitude', models.FloatField(default=0.0)),
                ('dropoff_longitude', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_rides', to='system.profile')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_rides', to='system.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ratings', to='system.profile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings', to='system.profile')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.riderequest')),
            ],
        ),
    ]
